[package]
name = "faux-unix-system"
description = "A unix terminal for your website"
version = "0.1.0"
authors = ["Property404 <dagan@dagans.dev>"]
edition = "2021"
repository = "https://github.com/Property404/its-a-unix-system"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
anyhow = "1.0.66"
console_error_panic_hook = { version = "0.1.6", optional = true }
futures = "0.3.25"
js-sys = "0.3.60"
wasm-bindgen = "0.2.63"
wasm-bindgen-futures = { version = "0.4.33", features = ["futures-core", "futures-core-03-stream"] }
web-sys = { version = "0.3.60", features = ["Document", "Window", "KeyboardEvent"] }
wee_alloc = { version = "0.4.5", optional = true }

# TODO: switch to crates.io version when 0.7.2 or later is out
[dependencies.vfs]
git = "https://github.com/manuel-woelker/rust-vfs"
branch = "master"

[build-dependencies]
anyhow = "1.0.66"
walkdir = "2.3.2"

[dev-dependencies]
wasm-bindgen-test = "0.3.13"
futures-test = "0.3.25"

[profile.release]
opt-level = "s"
lto = true
