[package]
name = "faux-unix-system"
description = "A unix terminal for your website"
version = "0.1.0"
authors = ["Property404 <dagan@dagans.dev>"]
edition = "2021"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.63"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.6", optional = true }

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
wee_alloc = { version = "0.4.5", optional = true }
web-sys = { version = "0.3.60", features = ["Element", "Document", "Window", "console", "KeyboardEvent"] }
anyhow = "1.0.66"
wasm-bindgen-futures = { version = "0.4.33", features = ["futures-core", "futures-core-03-stream"] }
js-sys = "0.3.60"
futures = "0.3.25"
futures-test = "0.3.25"

[dev-dependencies]
wasm-bindgen-test = "0.3.13"

[profile.release]
# Tell `rustc` to optimize for small code size.
#opt-level = "s"
opt-level = 0
