[package]
name = "faux-unix-system"
description = "A unix terminal for your website"
version = "0.1.0"
authors = ["Property404 <dagan@dagans.dev>"]
edition = "2021"
repository = "https://github.com/Property404/its-a-unix-system"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
anyhow = "1.0.66"
console_error_panic_hook = { version = "0.1.7", optional = true }
futures = "0.3.25"
getrandom = { version = "0.2.8", features = ["js"] }
js-sys = "0.3.60"
rand = "0.8.5"
wasm-bindgen = "0.2.83"
wasm-bindgen-futures = { version = "0.4.33", features = ["futures-core", "futures-core-03-stream"] }
web-sys = { version = "0.3.60", features = ["Document", "Window", "KeyboardEvent"] }
wee_alloc = { version = "0.4.5", optional = true }
textwrap = "0.16.0"

# TODO: switch to crates.io version when 0.7.2 or later is out
[dependencies.vfs]
git = "https://github.com/manuel-woelker/rust-vfs"
branch = "master"

[build-dependencies]
anyhow = "1.0.66"
walkdir = "2.3.2"
itertools = "0.10.5"

[dev-dependencies]
wasm-bindgen-test = "0.3.33"
futures-test = "0.3.25"

[profile.release]
opt-level = "s"
lto = true
