name: Release CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build
        run: |
          rustup target add wasm32-unknown-unknown
          cargo install wasm-pack
          wasm-pack build --no-default-features
          pushd www
          npm install
          npm run build
          popd
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: iaus-release
          path: www/dist
