---
name: Release CI

# yamllint disable-line rule:truthy
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build
        run: |
          rustup target add wasm32-unknown-unknown
          cargo install wasm-pack
          wasm-pack build --no-default-features
          pushd www
          npm install
          npm run build
          popd
      - name: Tar dist
        run: tar czf its-a-unix-system.tar.gz www/dist/
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: true
          prerelease: true
          release_name: ${{ github.ref }}
          tag_name: ${{ github.ref }}
          body: Look at me I'm a release haha
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./its-a-unix-system.tar.gz
          asset_name: its-a-unix-system.tar.gz
          asset_content_type: application/gzip
